version: "3.9"

services:

  truck:
      image: delivery-drone/truck
      ports:
        - "8085:8085"

  alpha:
      image: delivery-drone/drone
      ports:
        - "8084:8084"
      environment:
        - DRONE_HOST=alpha
      depends_on:
        - "truck"

  beta:
      image: delivery-drone/drone
      ports:
        - "8083:8084"
      environment:
        - DRONE_HOST=beta
      depends_on:
        - "truck"

  charly:
      image: delivery-drone/drone
      ports:
        - "8082:8084"
      environment:
        - DRONE_HOST=charly
      depends_on:
        - "truck"

  warehouse:
      image: delivery-drone/warehouse
      ports:
        - "8086:8086"