version: "3.9"

services:
  web:
      image: delivery-drone/truck
      depends_on:
        - database
      environment:
        - DATABASE_URL=postgres://root:password@database:5432/postgres
        - PORT=8080
      expose:
        - 8080
      ports:
        - "8080:8080"

  database:
    image: postgres:13.4
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root