version: "3.9"

services:
  web:
      image: si5-sacc/td1
      container_name: web
      depends_on:
        - database
      environment:
        - DATABASE_URL=postgres://si5_sacc:dev_password@database:5432/postgres
        - PORT=8080
      expose:
        - 8080
      ports:
        - "8080:8080"

  database:
    image: postgres:13.4
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=si5_sacc