version: "3.9"

services:

  map:
      image: delivery-drone/map
      ports:
        - "8081:8081"
        - "3000:3000"
      environment:
        - APP_ENV=prod

  ui:
      image: delivery-drone/ui
      ports:
        - "8080:8080"
      environment:
        - APP_ENV=prod

  truck:
      image: delivery-drone/truck
      ports:
        - "8085:8085"
      environment:
        - APP_ENV=prod

  drone-alpha:
      image: delivery-drone/drone
      ports:
        - "8087:8087"
      environment:
        - DRONE_NAME=alpha
        - DRONE_HOST=drone-alpha
        - DRONE_PORT=8087
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-beta:
      image: delivery-drone/drone
      ports:
        - "8088:8088"
      environment:
        - DRONE_NAME=beta
        - DRONE_HOST=drone-beta
        - DRONE_PORT=8088
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-charly:
      image: delivery-drone/drone
      ports:
        - "8089:8089"
      environment:
        - DRONE_NAME=charly
        - DRONE_HOST=drone-charly
        - DRONE_PORT=8089
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-gamma:
      image: delivery-drone/drone
      ports:
        - "8090:8090"
      environment:
        - DRONE_NAME=gamma
        - DRONE_HOST=drone-gamma
        - DRONE_PORT=8090
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-omicron:
      image: delivery-drone/drone
      ports:
        - "8091:8091"
      environment:
        - DRONE_NAME=omicron
        - DRONE_HOST=drone-omicron
        - DRONE_PORT=8091
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  warehouse:
      image: delivery-drone/warehouse
      ports:
        - "8086:8086"
      environment:
        - APP_ENV=prod