version: "3.9"

services:

  truck:
      image: delivery-drone/truck
      ports:
        - "8085:8085"
      environment:
        - APP_ENV=prod

  drone-alpha:
      image: delivery-drone/drone
      ports:
        - "8084:8084"
      environment:
        - DRONE_NAME=alpha
        - DRONE_HOST=drone-alpha
        - DRONE_PORT=8084
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-beta:
      image: delivery-drone/drone
      ports:
        - "8083:8083"
      environment:
        - DRONE_NAME=beta
        - DRONE_HOST=drone-beta
        - DRONE_PORT=8083
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  drone-charly:
      image: delivery-drone/drone
      ports:
        - "8082:8082"
      environment:
        - DRONE_NAME=charly
        - DRONE_HOST=drone-charly
        - DRONE_PORT=8082
        - DRONE_CAPACITY=1
        - APP_ENV=prod
      depends_on:
        - "truck"

  warehouse:
      image: delivery-drone/warehouse
      ports:
        - "8086:8086"
      environment:
        - APP_ENV=prod