const STARTING_DELIVERY=1;
const PENDING_DELIVERY=2;
const FINISHED_DELIVERY=3;
const PACKAGE_DELIVERED=4;

module.exports = {
    STARTING_DELIVERY,
    PENDING_DELIVERY,
    FINISHED_DELIVERY,
    PACKAGE_DELIVERED
}